feat: RSA_PKCS1_WITH_TLS_PADDING padding developped in the provider
latchset/pkcs11-provider pull request #392
Opened 2024-05-14 13:33 UTC by sebastienandert

Hi,  

I work in a company and for these 3 last months, we have worked on the embedding of the opensslv3 functions in our application.  
The aim of these implementation is to access to our HSM (Eviden) via opensslv3 functions in PKCS11 using your provider.  

Unfortunately, a test failed due to a function not implemented in your provider.  

# Missing function in the provider

When we connect an openssl s_client to an openssl s_server using these 2 commands :  
`./openssl s_server -port 4456 -provider pkcs11 -key "pkcs11:object=nom;id=1122334455-000000000000000000000000-98" -cert /int1/pki/store/user/crt/C2P_HSM_20261205.crt`  
and  
`./openssl s_client -connect 127.0.0.1:4456 -CApath /int1/pki/store/ac/crt_rehash -cipher AES128-GCM-SHA256`

We get the following error coming from Openssl libraries :

```c++
-----------------------------------------------------------------
Using default temp DH parameters
ACCEPT
ERROR
0011F0435A7F0000:error:1C8000A5:Provider routines:p11prov_rsaenc_set_ctx_params:illegal or unsupported padding mode:asymmetric_cipher.c:491:
0011F0435A7F0000:error:0A000093:SSL routines:tls_process_cke_rsa:decryption failed:ssl/statem/statem_srvr.c:2946:
CONNECTION CLOSED

In the openssl sources, this error comes from the function : 

openssl-3.0.11/ssl/statem/statem_srvr.c:tls_process_cke_rsa:2909
    if (EVP_PKEY_decrypt_init(ctx) <= 0
            || EVP_PKEY_CTX_set_rsa_padding(ctx, RSA_PKCS1_WITH_TLS_PADDING) <= 0) {
        SLfatal(s, SSL_AD_DECRYPT_ERROR, SSL_R_DECRYPTION_FAILED);
        goto err;
    }
-----------------------------------------------------------------
```

After inverstigating on this issue, it appears that ciphers using RSA key exchange type involves to use the padding : RSA_PKCS1_WITH_TLS_PADDING, which is not supported by your provider.
hence this error raises by your provider :

```c++
-----------------------------------------------------------------
0011F0435A7F0000:error:1C8000A5:Provider routines:p11prov_rsaenc_set_ctx_params:illegal or unsupported padding mode:asymmetric_cipher.c:491:

if (mechtype == CK_UNAVAILABLE_INFORMATION) {
    P11PROV_debug("mechtype == CK_UNAVAILABLE_INFORMATION");
    ERR_raise(ERR_LIB_PROV, PROV_R_ILLEGAL_OR_UNSUPPORTED_PADDING_MODE);
    return RET_OSSL_ERR;
}
-----------------------------------------------------------------
```

Then, we have implemented this unsupported padding (mandatory for our needs) in order to continue using you provider.  

It's now 1 month our improved provider runs under our UAT environment without error anymore.  
Of course we would like to share you our implementation and to know if you could integrate it in your sources in a near futur ?  

Thanks,
Kind regards,

2024-05-14 15:20 UTC, simo5 requested changes
Thanks for this PR, there is a lot to adjust, especially the actual core of the function is completely side-channel unsafe and will require careful rewrite.

Please avoid churn unnecessary to implement the actual feature when submitting a PR, it just makes it harded to review.

(Also I will not accept regressing from basic initialization features, if you need to support an old compiler that can't deal with initializers, then please keep that as a local patch to your environment for now)

2024-05-14 15:20 UTC, simo5 commented on src/asymmetric_cipher.c
> +    int alt_version;        /* RSA_PKCS1_WITH_TLS_PADDING: negociated_version */
These are passed as int by openssl for convenience, but are actually each a pair of 1 byte values.
I would either declare them as uint16_t or even better already split thme into the component bytes and declare a pair of uint8_t for each.

2024-05-14 15:20 UTC, simo5 commented on src/asymmetric_cipher.c
> +        ret = OSSL_PARAM_get_int(p, &encctx->alt_version);
same as above

2024-05-14 15:20 UTC, simo5 commented on src/encoder.c
> +    memset (&keypoint, 0, sizeof (keypoint));
please don't do this, the above initialization is just fine.

2024-05-14 15:20 UTC, simo5 commented on src/interface.c
> +        err = dlerror();
this change does not belong in this PR, please revert it.

2024-05-14 15:20 UTC, simo5 commented on src/interface.c
> +        err = dlerror();
this comment applies to all the changes in this file

2024-05-14 15:20 UTC, simo5 commented on src/interface.c
>      ret = MUTEX_LOCK(mctx);
don't do this the above initializations are just fine

2024-05-14 15:20 UTC, simo5 commented on src/kdf.c
> +#ifndef SIZE_MAX
If you do not have SIZE_MAX define it in a header, not in here.
What platform lacks this in a header?

2024-05-14 15:20 UTC, simo5 commented on src/objects.c
> +    memset (template, 0, sizeof (template));
again no, the original initialization is just fine.

2024-05-14 15:20 UTC, simo5 commented on src/objects.c
> +    memset (template, 0, sizeof (template));
I won't repeat it again for each occurence, but please revert all of these changes

2024-05-14 15:20 UTC, simo5 commented on src/provider.c
> +
Please remove this

2024-05-30 16:51 UTC, tomato42 commented
@sebastienandert wrote:
> It's now 1 month our improved provider runs under our UAT environment without error anymore.

there's a subtle difference between "it works" and "it's secure": https://people.redhat.com/~hkario/marvin/
this code is almost certainly vulnerable to side-channel attacks even if the HSM performs the private key operations in constant time (and that's an "if" in itself)

2024-05-31 16:58 UTC, simo5 commented
Given I saw no answers to the review, and the proposed change required major overhauls pretty much everywhere I went ahead and implemented it diffrently in PR #402 

Closing this one, thanks for the contribution.

2024-05-31 16:58 UTC, closed without merging