Update HOWTO.md
latchset/pkcs11-provider pull request #411
Opened 2024-06-28 22:18 UTC by karamellpelle

Elaborating some details

#### Description

I added some small clarifications/explanations about how to use _provider-pkcs11_. These explanations would have saved me from some hours of problems while setting up _provider_pkcs11_ on my system. 

I tried to write these additions concise and in similar wording.

#### Checklist

- [ ] Code modified for feature
- [ ] Test suite updated with functionality tests
- [ ] Test suite updated with negative tests
- [x] Documentation updated

#### Reviewer's checklist:

- [ ] Any issues marked for closing are addressed
- [ ] There is a test suite reasonably covering new functionality or modifications
- [ ] This feature/change has adequate documentation added
- [ ] Code conform to coding style that today cannot yet be enforced via the check style test
- [ ] Commits have short titles and sensible commit messages
- [ ] Coverity Scan has run if needed (code PR) and no new defects were found

2024-07-01 12:53 UTC, simo5 requested changes
Thank you, it is a welcome addition to our docs. Just one minor change required.

2024-07-01 12:53 UTC, simo5 commented on HOWTO.md
> +remember to activate it, otherwise the _openssl_ command will behave strange):
`will behave in a strange way`,
or
`will not behave correctly`

2024-07-01 15:02 UTC, karamellpelle reviewed
Improved sentence

2024-07-01 15:37 UTC, simo5 commented
It would be nice if you could squash the two commits, if you can't do that let me know and I will deal with it.

2024-07-01 20:11 UTC, karamellpelle commented
> It would be nice if you could squash the two commits, if you can't do that let me know and I will deal with it.

Yes, please do that (and modify the commit even more if you need to). I tried to squash (`git rebase -i HEAD~2` + and push back to my fork repository), but I wasn't able to make it work. I've never done _squashing_ before, and I have little experience with pull request, but it is fun to learn new workflows so I can be better at contributing to the open source community. 

Thanks!

2024-07-02 17:15 UTC, simo5 commented
I forced pushed the sqashed commits to your main branch.
You probably want to git pull --rebase locally, or something

2024-07-02 17:16 UTC, simo5 approved these changes

2024-07-02 17:19 UTC, merged